Algoritmo "EXERCICIO_PAG66_J"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : JAILSON
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : JOALDO
// Data atual  : 17/04/2024
Var
   celsius:inteiro
   fahrenheit: real
inicio
   para celsius de 10 ate 100 passo 10 faca
      fahrenheit <= (9/5) * celsius + 32
      escreval(celsius:1:0, " graus Celsius é igual a ", fahrenheit:1:2, " graus Fahrenheit.")
   fimpara
fimalgoritmo