Algoritmo "EXERCICIO_PAG41_K"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : joaldo
// Data atual  : 16/04/2024
Var
   num:inteiro

Inicio
   escreval ("digite um numero ate 3")
   leia (num)
   se (num < 3) entao
      Escreval("O numero e menor que tres")
   senao
   fimse
FimAlgoritmo