Algoritmo "EXERCICIO_PAG41_I"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : joaldo
// Data atual  : 16/04/2024
Var
   num:inteiro

Inicio
   escreval ("digite um numero")
   leia (num)
   se num mod 2 = 0 entao
      Escreval("O número ", num, " é par.")
   senao
      Escreval("O número ", num, " é ímpar.")
   fimse
FimAlgoritmo