Algoritmo "EXERCICIO_PAG46_D"
// Disciplina   : [Linguagem e Lógica com JS]
// Professor   : jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : joaldo
// Data atual  : 19/04/2024
Var
   numero: inteiro

Inicio
   enquanto numero <= 20 faca
      se numero mod 2 <> 0 Entao
         escreval(numero)
      fimSe
      numero <- numero + 1
   fimEnquanto

FimAlgoritmo