Algoritmo "EXERCICIO_PAG46_C"
// Disciplina   : [Linguagem e Lógica com JS]
// Professor   : jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : joaldo
// Data atual  : 19/04/2024
Var
   soma, numero: inteiro

Inicio
   numero <- 1
   enquanto numero <= 500 faca
      se numero mod 2 = 0 entao
         soma <- soma + numero
         escreval (numero , " a soma será:" , soma)
      fimSe
      numero <- numero + 1
   fimEnquanto

FimAlgoritmo