Algoritmo "EXERCICIO_K"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : real para dolar
// Autor(a)    : Joaldo
// Data atual  : 10/04/2024
Var
qtreal, IC, valor :real


Inicio
escreval ("insira a quantidade de reais que você tem")
leia (qtreal)
escreval ("qual o valor da cotação do dolar hoje")
leia (IC)
valor <- (qtreal / IC)
escreval ("O valor da transformação é $:", valor)

Fimalgoritmo