Algoritmo "EXERCICIO_PAG41_J"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : joaldo
// Data atual  : 16/04/2024
Var
   num:inteiro

Inicio
   escreval ("digite o valor de 1 até 9")
   leia (num)
   se (num >= 1) e (num <= 9) entao
      Escreval("O valor da faixa está permitida")
   senao
      Escreval("O valor da faixa está fora da faixa permitida")
   fimse
FimAlgoritmo