Algoritmo "EXERCICIO_PAG46_H"
// Disciplina   : [Linguagem e Lógica com JS]
// Professor   : jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : joaldo
// Data atual  : 19/04/2024
Var
   celsius, fahrenheit: real

Inicio
   celsius <- 10
   enquanto celsius <= 100 faca
      fahrenheit <- (9 * celsius / 5) + 32
      escreva("Celsius:",celsius, "  em Fahrenheit:",fahrenheit)
      celsius <- celsius + 10
      escreval("")
   fimEnquanto

FimAlgoritmo