Algoritmo "EXERCICIO_PAG46_B"
// Disciplina   : [Linguagem e Lógica com JS]
// Professor   : jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : joaldo
// Data atual  : 19/04/2024
Var
   numero, soma, contador: inteiro

Inicio
   contador <- 1
   enquanto contador <= 100 faca
      soma <- soma + contador
      escreval (contador, " a soma será:" ,soma)
      contador <- contador + 1
   fimEnquanto

FimAlgoritmo