Algoritmo "EXERCICIO_L"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Soma de 3 valores
// Autor(a)    : Joaldo
// Data atual  : 10/04/2024
Var
   A, B, C: real
   quadrado:real
Inicio
   escreval("Digite o valor de A:")
   leia(A)
   escreval("Digite o valor de B:")
   leia(B)
   escreval("Digite o valor de C:")
   leia(C)
   quadrado <- A*A + B*B + C*C
   escreval("A soma dos quadrados dos três valores é: ",quadrado)

Fimalgoritmo