Algoritmo "EXERCICIO_J"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : dolar para real
// Autor(a)    : Joaldo
// Data atual  : 10/04/2024
Var
qtdolar, IC, valor :real


Inicio
escreval ("insira a quantidade de dolares")
leia (qtdolar)
escreval ("qual o valor da cotação do dolar hoje")
leia (IC)
valor <- (qtdolar * IC)
escreval ("O valor da transformação é R$:", valor)

Fimalgoritmo